### ISSUE TITLE
Deploying to heroku gives issues.

### ISSUE THREAD

**Issue by prameshbajra** [ChatPlug/libfb-js#70]
> I am not sure if this is a place to ask this question.

The library works perfect in my local system but when I deploy it to Heroku I cannot get it to work. After the deployment, I have to verify my account on Facebook. I know that Heroku servers from `Austin, USA` are causing this problem (Location difference) but I was looking for something to bypass/workaround for this.

Has anyone faced this issue? And did anyone solved it?

Some help, please :)

**Comment by ptrcnull** [comment]
Hey, first of all, enabling 2-factor-authentication and using app passwords (you can find them in security settings) can help.
Secondly, Heroku is totally not recommended for this kind of stuff. Their sandboxes are being stopped when nobody visits the "website" you're supposed to host there.

**Comment by prameshbajra** [comment]
> Hey, first of all, enabling 2-factor-authentication and using app passwords (you can find them in security settings) can help. Secondly, Heroku is totally not recommended for this kind of stuff. Their sandboxes are being stopped when nobody visits the "website" you're supposed to host there.

Hi @ptrcnull , Thank you for the quick reply. I will definitely try this out. I am going to ping Heroku every 5 minutes, so sandboxes won't be a problem in my case I guess.

Any alternatives you recommend?

**Comment by prameshbajra** [comment]
Hi @ptrcnull , 
I tried with all the possible combinations for 2-factor authentication that facebook provides but got no luck. It asked me if `It was me that was logging in to my facebook from Austin, USA?` but even after clicking yes, I was not able to get it to run.

I kept asking me to verify my account. Any help with this?

**Comment by ptrcnull** [comment]
Hey, did you try *app passwords* as I said? See [here](https://www.facebook.com/settings?tab=security&section=per_app_passwords)
